# Generated by Django 4.0.6 on 2022-08-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('order_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(max_length=200)),
                ('mid', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInitialized',
            fields=[
                ('order_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mid', models.IntegerField()),
                ('amount', models.FloatField()),
                ('actual_amount', models.FloatField()),
                ('gid', models.CharField(max_length=200)),
                ('g_password', models.CharField(max_length=50)),
            ],
        ),
    ]
