# Generated by Django 4.0.6 on 2022-07-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billed_by',
            field=models.IntegerField(default=0),
        ),
    ]
