# Generated by Django 4.0.6 on 2022-07-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Details',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('g_name', models.CharField(max_length=200)),
                ('g_password', models.CharField(max_length=50)),
                ('g_members', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Members',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField(default=0)),
                ('m_name', models.CharField(max_length=200)),
            ],
        ),
    ]
