# Generated by Django 4.0.6 on 2022-07-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_members',
            name='wallet_balance',
            field=models.FloatField(default=0),
        ),
    ]
