# Generated by Django 4.0.6 on 2022-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_members_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBillClear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared_bill_ids', models.IntegerField(default=0)),
                ('mid', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=100)),
                ('bill_amount', models.IntegerField()),
                ('payout_method', models.CharField(max_length=50)),
                ('payout_details', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('P', 'Pending Payout'), ('S', 'Payout Sent')], max_length=2)),
            ],
        ),
    ]
