# Generated by Django 4.0.6 on 2022-08-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_adminbillclear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminbillclear',
            name='status',
        ),
    ]
