# Generated by Django 4.0.6 on 2022-07-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberPayout',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('upi', models.CharField(max_length=200, null=True)),
                ('account_number', models.CharField(max_length=100, null=True)),
                ('account_name', models.CharField(max_length=30, null=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('paytm_number', models.IntegerField(null=True)),
                ('receiving_preference', models.CharField(max_length=2)),
            ],
        ),
    ]
